# Generated by Django 3.2.9 on 2021-12-03 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('bags', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat', models.CharField(max_length=3)),
                ('cabin', models.CharField(max_length=10)),
                ('zone', models.CharField(max_length=3)),
                ('gate', models.CharField(max_length=3)),
                ('date', models.CharField(max_length=8)),
                ('boarding_time', models.CharField(max_length=10)),
                ('depart_time', models.CharField(max_length=10)),
                ('confirmation_number', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=1)),
                ('checked_in', models.BooleanField()),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retrieve_api.passenger')),
            ],
        ),
    ]
