# Generated by Django 3.2.9 on 2021-12-05 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retrieve_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='checked_in',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='flight',
            name='gate',
            field=models.CharField(max_length=4),
        ),
    ]
