# Generated by Django 3.2.9 on 2021-12-06 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retrieve_api', '0002_auto_20211205_1644'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passenger',
            name='name',
        ),
        migrations.AddField(
            model_name='passenger',
            name='first_name',
            field=models.CharField(default='John', max_length=100),
        ),
        migrations.AddField(
            model_name='passenger',
            name='last_name',
            field=models.CharField(default='Doe', max_length=100),
        ),
    ]
