# Generated by Django 3.2.9 on 2021-12-07 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retrieve_api', '0004_flight_airline'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='Cookie God', max_length=200)),
                ('score', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='Flight',
        ),
        migrations.DeleteModel(
            name='Passenger',
        ),
    ]
